export const LEVEL_OPTIONS = [
  "Primary 1",
  "Primary 2",
  "Primary 3",
  "Primary 4",
  "Primary 5",
  "Primary 6",
  "Secondary 1",
  "Secondary 2",
  "Secondary 3",
  "Secondary 4",
  "JC 1",
  "JC 2",
  "IBDP Year 1",
  "IBDP Year 2",
  "Diploma / Polytechnic",
  "University",
  "Adult / Others",
];
