import { jsPDF } from "jspdf";
import { formatSGD } from "./paymentNotice";
import { reportFilenameBase } from "./monthlyReport";

// jsPDF's built-in fonts only support WinAnsi encoding, which has no emoji
// glyphs — render them as mangled bytes instead of failing silently, so
// strip them out of any text drawn into the PDF.
function stripEmoji(text) {
  return text
    .replace(/[\u{1F000}-\u{1FFFF}\u{2190}-\u{2BFF}\u{2600}-\u{27BF}]/gu, "")
    .replace(/️/gu, "")
    .trim();
}

export function downloadMonthlyReportPdf(monthDate, tutorName, report) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = 56;

  const monthLabel = monthDate.toLocaleDateString("en-SG", {
    month: "long",
    year: "numeric",
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(22, 101, 52);
  doc.text("ChopeAndPay — Monthly Report", margin, y);

  y += 22;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(`${tutorName || "Tutor"} · ${monthLabel}`, margin, y);

  y += 28;
  doc.setDrawColor(220, 220, 220);
  doc.line(margin, y, pageWidth - margin, y);

  y += 28;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(17, 24, 39);
  doc.text("Summary", margin, y);

  y += 20;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(55, 65, 81);
  doc.text(`Total lessons taught: ${report.totalLessons}`, margin, y);
  y += 18;
  doc.text(`Total amount collected: ${formatSGD(report.collected)}`, margin, y);
  y += 18;
  doc.text(`Total amount pending: ${formatSGD(report.pending)}`, margin, y);

  y += 32;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(17, 24, 39);
  doc.text("Per-student breakdown", margin, y);

  y += 18;
  const colX = {
    name: margin,
    subject: margin + 120,
    level: margin + 220,
    lessons: margin + 300,
    paid: margin + 370,
    pending: margin + 450,
  };
  const headerY = y;
  doc.setFillColor(240, 253, 244);
  doc.rect(margin, headerY - 12, pageWidth - margin * 2, 20, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(22, 101, 52);
  doc.text("Student", colX.name, y);
  doc.text("Subject", colX.subject, y);
  doc.text("Level", colX.level, y);
  doc.text("Lessons", colX.lessons, y);
  doc.text("Paid", colX.paid, y);
  doc.text("Pending", colX.pending, y);

  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(55, 65, 81);
  if (report.perStudent.length === 0) {
    doc.text("No lessons recorded this month.", margin, y);
    y += 18;
  } else {
    for (const row of report.perStudent) {
      if (y > 740) {
        doc.addPage();
        y = 56;
      }
      doc.text(row.name, colX.name, y, { maxWidth: 115 });
      doc.text(row.subject || "—", colX.subject, y, { maxWidth: 95 });
      doc.text(row.level || "—", colX.level, y, { maxWidth: 75 });
      doc.text(String(row.lessonsCount), colX.lessons, y);
      doc.text(formatSGD(row.amountPaid), colX.paid, y);
      doc.text(formatSGD(row.amountPending), colX.pending, y);
      y += 18;
    }
  }

  y += 24;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(22, 101, 52);
  doc.text(stripEmoji(report.message), margin, y);

  const footerY = doc.internal.pageSize.getHeight() - 36;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(156, 163, 175);
  doc.text("Generated by ChopeAndPay · chopeandpay.com", margin, footerY);

  doc.save(reportFilenameBase(monthDate, "pdf"));
}
