import { forwardRef } from "react";
import { formatSGD } from "../lib/paymentNotice";

const MonthlyReportTemplate = forwardRef(function MonthlyReportTemplate(
  { tutorName, monthLabel, report },
  ref,
) {
  return (
    <div
      ref={ref}
      style={{
        position: "fixed",
        top: 0,
        left: "-9999px",
        width: "640px",
        background: "#ffffff",
        padding: "32px",
        fontFamily: "Helvetica, Arial, sans-serif",
        color: "#111827",
      }}
    >
      <h1 style={{ margin: 0, fontSize: "22px", color: "#15803d" }}>
        TuitionPayLah — Monthly Report
      </h1>
      <p style={{ margin: "6px 0 20px", fontSize: "14px", color: "#4b5563" }}>
        {tutorName || "Tutor"} · {monthLabel}
      </p>
      <div style={{ borderTop: "1px solid #e5e7eb", margin: "0 0 20px" }} />

      <h2 style={{ fontSize: "16px", margin: "0 0 10px", color: "#111827" }}>
        Summary
      </h2>
      <p style={{ fontSize: "13px", margin: "0 0 4px", color: "#374151" }}>
        Total lessons taught: {report.totalLessons}
      </p>
      <p style={{ fontSize: "13px", margin: "0 0 4px", color: "#374151" }}>
        Total amount collected: {formatSGD(report.collected)}
      </p>
      <p style={{ fontSize: "13px", margin: "0 0 20px", color: "#374151" }}>
        Total amount pending: {formatSGD(report.pending)}
      </p>

      <h2 style={{ fontSize: "16px", margin: "0 0 10px", color: "#111827" }}>
        Per-student breakdown
      </h2>
      <table
        style={{
          width: "100%",
          fontSize: "12px",
          borderCollapse: "collapse",
          marginBottom: "24px",
        }}
      >
        <thead>
          <tr style={{ background: "#f0fdf4", color: "#15803d" }}>
            <th style={{ textAlign: "left", padding: "6px 8px" }}>Student</th>
            <th style={{ textAlign: "left", padding: "6px 8px" }}>Subject</th>
            <th style={{ textAlign: "left", padding: "6px 8px" }}>Level</th>
            <th style={{ textAlign: "right", padding: "6px 8px" }}>Lessons</th>
            <th style={{ textAlign: "right", padding: "6px 8px" }}>Paid</th>
            <th style={{ textAlign: "right", padding: "6px 8px" }}>Pending</th>
          </tr>
        </thead>
        <tbody>
          {report.perStudent.length === 0 ? (
            <tr>
              <td colSpan={6} style={{ padding: "8px", color: "#6b7280" }}>
                No lessons recorded this month.
              </td>
            </tr>
          ) : (
            report.perStudent.map((row) => (
              <tr
                key={row.studentId}
                style={{ borderTop: "1px solid #f3f4f6" }}
              >
                <td style={{ padding: "6px 8px" }}>{row.name}</td>
                <td style={{ padding: "6px 8px" }}>{row.subject || "—"}</td>
                <td style={{ padding: "6px 8px" }}>{row.level || "—"}</td>
                <td style={{ padding: "6px 8px", textAlign: "right" }}>
                  {row.lessonsCount}
                </td>
                <td style={{ padding: "6px 8px", textAlign: "right" }}>
                  {formatSGD(row.amountPaid)}
                </td>
                <td style={{ padding: "6px 8px", textAlign: "right" }}>
                  {formatSGD(row.amountPending)}
                </td>
              </tr>
            ))
          )}
        </tbody>
      </table>

      <p
        style={{
          fontSize: "15px",
          fontWeight: 600,
          color: "#15803d",
          margin: "0 0 28px",
        }}
      >
        {report.message}
      </p>

      <p style={{ fontSize: "11px", color: "#9ca3af", margin: 0 }}>
        Generated by TuitionPayLah · tuitionpaylah.com
      </p>
    </div>
  );
});

export default MonthlyReportTemplate;
